
community_task:
  description: >
    Find relevant keyword based on the {user_query} and provide a list of recommended communities based on the keyword.
    This could include professional groups, forums, local meetups, and online communities. Also share the links to these communities.
  expected_output: >
    A list with keyword relevant communities, including their names, links, and a brief description of each community.
  agent: community_agent
 