recommend_learning_task:
  description: >
    Based on the user query : {user_query} cohort: {cohort} , background and identified skill gaps or aspirations if any.
    suggest learning resources, including courses, articles, events, and youtube videos.
    If the user is explicity mentioning the free and youtube keywords, then suggest free resources or youtube videos only.
    for women in career transition or growth based on their career roadmap.

  expected_output: >
    A list of:
      - curated courses/tutorials related to the user query or goals.
      - Totally Optional if not available: upcoming events or webinars 
    

  agent: learning_advisor