job_search_task:
  description: >
    This is the users profile skills : {skills} , location : {location} , cohort: {cohort} 
    if experience is mentioned in the user profile, then map Early if 0-3 years of experience,
    Mid if 3-5 years of experience and Senior if 5+ years of experience.
    If experience is not mentioned use cohort mapping.
    Cohort mapping:
    -  Starter : Early
    -  Riser : Mid
    -  Restarter : Mid, Senior 

    use contextTool to fetch relevant skills/keywords/interests and location user might be interested in 
    and only consider for users responds. 
    I repeat **do not cosnider AI response from contextTool.**
    Use both tools - JobAPITool and herkey_job_tool to query apis to fetch relevant job opportunities 
    for women using above mentioned skills/keywords/interests and location and experience
    The response should be tailored to the user's profile and preferences.

  expected_output: >
    **Strictly follow the format below and return jobs**
    Return only top 5 most relevant jobs in a list format with the following details:
      - Job title and description
      - Company name
      - Location (remote/on-site)
      - Application URL - if not available in the job description do not include.
      - years of experience required
      - skills required
    in very concise and conversational format.

  agent: job_search_agent

