job_search_task:
  description: >
    This is the users profile skills : {skills} , location : {location} and if in user query {user_query} company is given
    then use it to filter the jobs.
    query external job APIs or platforms and return a curated list of relevant job opportunities for women.
    
    *Use can also use contextTool to fetch relevant skills and location user might be interested in
    and  fetch jobs for them using JobAPITool and HerKeyJobAPITool*

  expected_output: >
    Return all relevant jobs in a list format with the following details:
      - Job title and description
      - Company name
      - Location (remote/on-site)
      - Application URL - important
      - years of experience required
      - skills required
      
    in very concise and conversational format.
    The list should be tailored to the user's profile and preferences.

  agent: job_search_agent

