job_search_task:
  description: >
    This is the users profile skills : {skills} , location : {location} (Remember skills and location could be empty.) 
    so if in user query {user_query} company is given then use it to filter the jobs or use contextTool to fetch relevant skills, keywords and location user might be interested in.
    Using JobAPIJobAPITool and herkey_job_tool query apis to fetch relevant job opportunities for women using those keywords and skills.
    The response should be tailored to the user's profile and preferences.

  expected_output: >
    Return top 5 most relevant jobs in a list format with the following details:
      - Job title and description
      - Company name
      - Location (remote/on-site)
      - Application URL - important
      - years of experience required
      - skills required
    in very concise and conversational format.

  agent: job_search_agent

