
conversational_task:
  description: >
    This is the {user_query} and the user is a {cohort} cohort and the user is looking for a {intent}.
    if intent is conversation_continues which means you need to continue the conversation with the user using the context_tool.
    Have a thoughtful, motivating, and context-aware conversation with the user.
    Ask about their career goals, past experience, and current challenges and their aspirations.
    Encourage them using stories of successful women in similar situations.
    Ask if they are interested in learning about job opportunities and learning resources.
    or need help in resume analysis.
    If the user query is not related career, return I cannot help you with that.

  expected_output: >
  
    A response in string form: The tone should be natural, motivational, guiding giving reply to the user and 
    if the user query is not related career, return I cannot help you with that.

  Target audience: Women in their career journey

  agent: conversational_agent
